### ISSUE TITLE
I have an "ImportError: No module named serial"

### ISSUE THREAD

**Issue by ninettyone** [anaganisk/johnny-five-esp8266#1]
A got this in my terminal:

$ python esptool.py --port /dev/tty.SLAB_USBtoUART erase_flash
Traceback (most recent call last):
  File "esptool.py", line 26, in <module>
    import serial
ImportError: No module named serial

:c

**Comment by anaganisk** [comment]
serial module isn't included with python, please run

pip install pyserial

and retry


- Best,
*Sai Kiran Anagani.*


On 08-Nov-2017 at 12:39 AM, eaguilarsaa <notifications@github.com> wrote:


A got this in my terminal:

$ python esptool.py --port /dev/tty.SLAB_USBtoUART erase_flash
Traceback (most recent call last):
File "esptool.py", line 26, in
import serial
ImportError: No module named serial

:c

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/anaganisk/johnny-five-esp8266/issues/1>, or mute the
thread
