### ISSUE TITLE
Esp8266 sleep problem

### ISSUE THREAD

**Issue by jimmyex500sl** [anaganisk/johnny-five-esp8266#2]
I just finished trying the tutorial, but had an issue that the ESP8266 go to sleep after left it runs for few hour.

Is there a way to make it stop going to sleep mode

**Comment by anaganisk** [comment]
Unless you explicitly add a code to send it to sleep, the esp8266  never goes into sleep mode.
So can you please check if there any such thing?

**Comment by jimmyex500sl** [comment]
Ok 
But something is not right that I finish testing with it and go to do something else.(Leave it power on for like 30 minutes or so)
And come back to test it again then it doesn't do the command that I write in the .js file, I try to ping it and it's not online so???

Is it go to sleep mode or there is something wrong with my network configuration?

I test it in two network configuration one is under 192.168.XXX.XXX, other is under 172.23.XXX.XXX

**Comment by anaganisk** [comment]
Sometimes this can happen because of the power supply too, so please check if you are supplying constant power to your esp. Is your ESP power through usb, connected to a laptop that goes into a sleep mode? That could just be an example, esp requires a constant stable supply, please check and let me know. I am quite sure that esp doesn't go to sleep unless you instruct it to.

**Comment by jimmyex500sl** [comment]
Ok I will try it on different power source. Than see what happen.

**Comment by jimmyex500sl** [comment]
After changing the power source the ESP8266 won't go to sleep.
I guess that because the laptop try to save power so it cut off the power, just like you said.

Thanks for your help.

**Comment by anaganisk** [comment]
Great! Closing this issue.
